language: java
jdk:
  - openjdk14
install:
  - sudo apt-get install -y ant ant-optional
services:
  - mysql
script: "ant all"
sudo: required
before_script:
  - bash .travis.install-mysql-5.7.sh
  - mysql -u root < etc/sql/schema.sql