name: Test

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: 14
          distribution: 'adopt'
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -uroot -proot < etc/sql/schema.sql
      - name: Run Tests
        run: ant all